# Generated by Django 3.2.5 on 2021-11-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_club'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
