# Generated by Django 3.2.9 on 2021-11-28 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_alter_user_options'),
        ('clubs', '0008_application_club'),
    ]

    operations = [
    ]
