# Generated by Django 3.2.5 on 2021-12-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_rename_result_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Player1', "Player 1's Win"), ('Player2', "Player 2's Win"), ('Draw', 'Draw'), ('Cancelled', 'Cancelled')], default='Pending', max_length=15),
        ),
    ]
